### PR TITLE
Fix version timestamp issue

### LINKED ISSUE #581: python api lists the same timestamp for all versions of a dataset
Hi - I ran into this issue while trying to make a PR for #506 .

The `versions` method on a Lance dataset returns the same timestamp for all the versions, despite them being written with >1s intervals. 

Repro:

```py
import shutil
import time
from datetime import datetime

import lance
import pandas as pd
import pyarrow as pa

# create a new dataset and append to it two more times
base_dir = "test_asof"
shutil.rmtree(base_dir, ignore_errors=True)

table = pa.Table.from_pydict({"colA": [1, 2, 3], "colB": [4, 5, 6]})
ds = lance.write_dataset(table, base_dir, mode="create")

time.sleep(1)
ds = lance.write_dataset(table, base_dir, mode="append")

time.sleep(1)
ds = lance.write_dataset(table, base_dir, mode="append")

print(ds.versions())
```

This produces the following, which is the `datetime.now()` value for all versions. 
```txt
[{'version': 1,
  'timestamp': datetime.datetime(2023, 2, 14, 19, 56, 29),
  'metadata': {}},
 {'version': 3,
  'timestamp': datetime.datetime(2023, 2, 14, 19, 56, 29),
  'metadata': {}},
 {'version': 2,
  'timestamp': datetime.datetime(2023, 2, 14, 19, 56, 29),
  'metadata': {}}]
```

Looking at the modified times for the 3 different manifests confirms there is no overwriting, the python API is seemingly reading it incorrectly. 

```py
import os

for i in (1, 2, 3):
    print(datetime.fromtimestamp(os.path.getmtime(f"test_asof/_versions/{i}.manifest")))
```

```txt
2023-02-14 19:50:54.074557
2023-02-14 19:50:55.097677
2023-02-14 19:50:56.111796
```

### PR DESCRIPTION
**Pull request by changhiskhan**
Closes #581

@ananis25  thanks again for the bug report

### CODE REVIEW

File: rust/src/format/manifest.rs [hunk 1]
```diff
@@ -44,16 +46,29 @@ pub struct Manifest {
 
     /// The file position of the index metadata.
     pub index_section: Option<usize>,
+
+    /// The creation timestamp with nanosecond resolution as 128-bit integer
+    pub timestamp_nanos: u128,
```
Comment (eddyxu) [inline rust/src/format/manifest.rs:51]: Provide an access method to access timestamp in native rust type?

File: rust/src/format/manifest.rs [hunk 2]
```diff
@@ -44,16 +46,29 @@ pub struct Manifest {
...
+
+    /// An optional string tag for this version
+    pub tag: Option<String>,
 }
 
 impl Manifest {
     pub fn new(schema: &Schema, fragments: Arc<Vec<Fragment>>) -> Self {
+        let duration_since_epoch = SystemTime::now()
```
Comment (eddyxu) [inline rust/src/format/manifest.rs:59]: This timestamp should be generated right before the commit (where the manifest is written AFTER all data is written).

**Review by eddyxu — COMMENTED** [review]
Mostly about when the timestamp is genereated. the rest LGTM.

**Review by eddyxu — APPROVED** [review]
LGTM. Thanks
