### PR TITLE
Handle null strings for both cases where nullability is set or not.

### LINKED ISSUE #507: Null string crashes reading oxford pet
```python

oxford_pet = lance.dataset('s3://eto-public/datasets/oxford_pet/oxford_pet.lance')
duckdb.query("""
SELECT class, count(1) as cnt 
FROM oxford_pet 
GROUP BY 1
""").to_df().head()

```

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("non-nullable child of type Utf8 contains nulls not present in parent Struct([Field { name: \"database\", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"annotation\", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"image\", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }])")', /Users/lei/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-array-31.0.0/src/array/struct_array.rs:239:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by eddyxu**
Closes #507

### CODE REVIEW

File: rust/src/encodings/binary.rs [hunk 1]
```diff
@@ -223,32 +232,38 @@ impl<'a, T: ByteArrayType> AsyncIndex<Range<usize>> for BinaryDecoder<'a, T> {
...
             .len(index.len())
-            .null_count(null_count)
-            .null_bit_buffer(Some(null_buf.into()))
+            .null_count(0);
+
+        // Count nulls
+        if self.nullable {
+            let mut null_count = 0;
+            let mut null_buf = MutableBuffer::new_null(self.length);
+            int64_positions
```
Comment (changhiskhan) [inline rust/src/encodings/binary.rs:249]: This feels like a big perf hit?

**Review by changhiskhan — APPROVED** [review]

File: rust/src/encodings/binary.rs (hunk 1 above)
Comment (eddyxu) [reply rust/src/encodings/binary.rs:249]: This should still be way faster than reading a `bitmap` out of disk / s3.
