### PR TITLE
[C++] Performance profiling and improvement 

### LINKED ISSUE #292: possible performance regression?
the second one used to be very fast but is now on par with going straight through duckdb

image

### PR DESCRIPTION
**Pull request by eddyxu**
```
SELECT image, class FROM oxford_pet WHERE class = 'pud' LIMIT 20 OFFSET 50
```
Before this PR:  8.1s
After: 0.85s

Closes #292

### CODE REVIEW

File: cpp/benchmarks/bench_utils.cc [hunk 1]
```diff
@@ -81,13 +83,13 @@ std::shared_ptr<::arrow::io::RandomAccessFile> OpenUri(const std::string& uri, b
 }
 
 /// Open Dataset from the URI.
-std::shared_ptr<::arrow::dataset::FileSystemDataset> OpenDataset(const std::string& uri,
+std::shared_ptr<::arrow::dataset::Dataset> OpenDataset(const std::string& uri,
                                                                  const std::string& format) {
```
Comment (changhiskhan) [inline cpp/benchmarks/bench_utils.cc:87]: nit: indent?

**Review by changhiskhan — APPROVED** [review]

**Comment by eddyxu** [comment]
In comparison, running `python/benchmarks/oxford_pet/analytics.py -f parquet s3://eto-public/datasets/oxford_pet`

```
Function filter_data() {'base_uri': 's3://eto-public/datasets/oxford_pet', 'fmt': 'parquet', 'flavor': None} Took 173.1500 seconds
```
