### PR TITLE
[Bug] Calculating the nulls from position slices in chunks.

### LINKED ISSUE #843: [Bug] Var-length binary throw errors when there are null values.
```
ArrowInvalid: C Data interface error: Io error: Execution error: LanceError(I/O): Execution error: LanceError(Arrow): Invalid argument error: null_count 3483 for an array exceeds length of 2230 elements
```

### PR DESCRIPTION
**Pull request by eddyxu**
Closes #843

### CODE REVIEW

File: rust/src/encodings/binary.rs [hunk 1]
```diff
@@ -74,7 +74,7 @@ impl<'a> BinaryEncoder<'a> {
             let end = offsets[offsets.len() - 1].as_usize();
             let b = unsafe {
                 std::slice::from_raw_parts(
-                    arr.to_data().buffers()[1].as_ptr().offset(start as isize),
+                    arr.to_data().buffers()[1].as_ptr().add(start),
```
Comment (eddyxu) [inline rust/src/encodings/binary.rs:77]: `cargo clippy`

File: rust/src/encodings/binary.rs [hunk 2]
```diff
@@ -86,7 +86,7 @@ impl<'a> BinaryEncoder<'a> {
                 .skip(1)
                 .map(|b| b.as_usize() - start_offset + last_offset)
                 .for_each(|o| pos_builder.append_value(o as i64));
-            last_offset = pos_builder.values_slice()[pos_builder.len() - 1 as usize] as usize;
+            last_offset = pos_builder.values_slice()[pos_builder.len() - 1] as usize;
```
Comment (eddyxu) [inline rust/src/encodings/binary.rs:89]: `cargo clippy`

**Review by changhiskhan — APPROVED** [review]
