### PR TITLE
Pass filter indices via Limit and Return empty array in GetListArray

### LINKED ISSUE #188: Scanner errors / segfault
Setup:

```python
import lance
uri = "s3://eto-public/datasets/oxford_pet/oxford_pet.lance"
ds = lance.dataset(uri)
```

Head works fine:
```python
ds.head(10)
# ds.scanner(limit=10).to_table()
```

Filter alone raises Exception:
```python
In [9]: import pyarrow.compute as pc

In [10]: expr = pc.field("class") == "samoyed"

In [11]: ds.scanner(filter=expr).to_table()
---------------------------------------------------------------------------
ArrowIndexError                           Traceback (most recent call last)
Cell In [11], line 1
----> 1 ds.scanner(filter=expr).to_table()

File /mnt/lance/.venv/lance/lib/python3.10/site-packages/pyarrow/_dataset.pyx:2577, in pyarrow._dataset.Scanner.to_table()

File /mnt/lance/.venv/lance/lib/python3.10/site-packages/pyarrow/error.pxi:144, in pyarrow.lib.pyarrow_internal_check_status()

File /mnt/lance/.venv/lance/lib/python3.10/site-packages/pyarrow/error.pxi:127, in pyarrow.lib.check_status()

ArrowIndexError: FileReader::GetListArray: indices is empty: field=object(15)
```

Filter + Limit causes segfault:
```python
In [12]: ds.scanner(filter=expr, limit=10).to_table()
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by eddyxu**
Closes #188

### CODE REVIEW

File: cpp/src/lance/io/exec/limit.cc [hunk 1]
```diff
@@ -55,14 +56,23 @@ ::arrow::Result<ScanBatch> Limit::Next() {
   auto left = std::max(offset_, seen_);
   auto right = std::min(seen_ + batch_size, offset_ + limit_);
   std::shared_ptr<::arrow::RecordBatch> record_batch;
+  std::shared_ptr<::arrow::Array> indices;
   if (left < right) {
     record_batch = batch.batch->Slice(left - seen_, right - left);
+    if (batch.indices) {
+      indices = batch.indices->Slice(left - seen_, right - left);
```
Comment (changhiskhan) [inline cpp/src/lance/io/exec/limit.cc:63]: batch is our ScanBatch abstraction right? Would it make sense to create a batch.Slice that returns a structure with batch/indices as appropriate?

Comment (eddyxu) [reply cpp/src/lance/io/exec/limit.cc]: Fixed.

**Review by changhiskhan — APPROVED** [review]
