### PR TITLE
Fix bug that attempt to partitioned columns which does not exist in the file.

### LINKED ISSUE #185: Invalid group by over partitioned field
# Problem Statement

We have a partitioned dataset 

```
s3://path/to/oxford_pet.lance
   /train/*.lance
   /eval/*.lance
  ...
```

```python
dataset = lance.dataset(
        "s3://eto-public/datasets/oxford_pet/oxford_pet.lance",
        partitioning=pa.dataset.partitioning(field_names=["split"])
    )
duckdb.query("""
        SELECT
            count(1) as cnt, class, split
        FROM dataset
        GROUP BY 3, 2 ORDER BY class
    """

```

Raises

```
Failed example:
    print(duckdb.query("""
        SELECT
            count(1) as cnt, class, split
        FROM dataset
        GROUP BY 3, 2 ORDER BY class
    """).df())
Exception raised:
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 6, in <module>
        """).df())
    duckdb.InvalidInputException: Invalid Input Error: arrow_scan: get_next failed(): Invalid: Field split dose not exist
```

### PR DESCRIPTION
**Pull request by eddyxu**
Closes #185

### CODE REVIEW

File: cpp/src/lance/format/schema.cc [hunk 1]
```diff
@@ -477,7 +477,7 @@ ::arrow::Result<std::shared_ptr<Schema>> Schema::Project(
 
     auto actual_field = GetField(components[0]);
     if (!actual_field) {
-      return ::arrow::Status::Invalid("Field {} does not exist.", name);
+      continue;
```
Comment (changhiskhan) [inline cpp/src/lance/format/schema.cc:480]: Is this safe? Is this case always legitimate?

Comment (eddyxu) [reply cpp/src/lance/format/schema.cc:480]: Arrow strips out the partitioned columns, so the schema of these partitioned columns do not exist in the file.
As a result, from the file reader aspect, there is no reliable way to decide whether these columns are partitioned, or some columns that do not exist. 

We can add one test to verify it.

**Review by changhiskhan — APPROVED** [review]
pending the additional test to ensure an actual invalid column is caught "upstream"
